create table if not exists public.quotations (id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id),version int default 1,items jsonb not null default '[]',total_amount numeric(14,2),status text default '草稿',created_by uuid references public.profiles(id),created_at timestamptz default now());
create table if not exists public.contracts (id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id),contract_no text unique,total_amount numeric(14,2),deposit_amount numeric(14,2),order_payment_amount numeric(14,2),final_payment_amount numeric(14,2),signed_at date,created_at timestamptz default now());
create table if not exists public.order_costs (id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id),cost_type text not null,amount numeric(14,2) not null,supplier text,status text default '待确认',created_by uuid references public.profiles(id),created_at timestamptz default now());
create table if not exists public.store_expenses (id uuid primary key default gen_random_uuid(),category text not null,amount numeric(14,2) not null,payee text,expense_date date not null,description text,status text default '待审核',created_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),created_at timestamptz default now());
alter table public.quotations enable row level security;alter table public.contracts enable row level security;alter table public.order_costs enable row level security;alter table public.store_expenses enable row level security;
drop policy if exists "finance quotations" on public.quotations;create policy "finance quotations" on public.quotations for all using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "finance contracts" on public.contracts;create policy "finance contracts" on public.contracts for all using ((select role from public.my_profile()) in ('owner','finance','admin','manager')) with check (auth.uid() is not null);
drop policy if exists "finance costs" on public.order_costs;create policy "finance costs" on public.order_costs for all using ((select role from public.my_profile()) in ('owner','finance')) with check ((select role from public.my_profile()) in ('owner','finance'));
drop policy if exists "finance expenses" on public.store_expenses;create policy "finance expenses" on public.store_expenses for all using ((select role from public.my_profile()) in ('owner','finance')) with check ((select role from public.my_profile()) in ('owner','finance'));
